

const ALERT =  "ALERT"
const REFRETCH_CHAT = "REFRETCH_CHAT"
const NEW_ATTACHMENT = "NEW_ATTACHMENT"
const NEW_MESSAGE_ALERT = "NEW_MESSAGE"
const NEW_REQUEST = "NEW_REQUEST"
const CHAT_JOINED = "CHAT_JOINED"
const CHAT_LEAVED = "LEAVED"
const NEW_MESSAGE = "NEW_MESSAGE"
const START_TYPING = "START_TYPING"

const STOP_TYPING = "STOP_TYPING"



export {ALERT,CHAT_LEAVED,REFRETCH_CHAT,CHAT_JOINED,NEW_MESSAGE_ALERT,NEW_ATTACHMENT,NEW_REQUEST,NEW_MESSAGE,STOP_TYPING,START_TYPING}