

const ALERT =  "ALERT"
const REFRETCH_CHAT = "REFRETCH_CHAT"
const NEW_ATTACHMENT = "NEW_ATTACHMENT"
const NEW_MESSAGE_ALERT = "NEW_MESSAGE"
const NEW_REQUEST = "NEW_REQUEST"
const NEW_MESSAGE = "NEW_MESSAGE"

const START_TYPING = "START_TYPING"

const STOP_TYPING = "STOP_TYPING"


const CHAT_JOINED = "CHAT_JOINED";
const CHAT_LEAVED = "CHAT_LEAVED";

const ONLINE_USERS = "ONLINE_USERS";



export {ALERT,REFRETCH_CHAT,NEW_MESSAGE_ALERT,NEW_ATTACHMENT,NEW_REQUEST,CHAT_JOINED,CHAT_LEAVED,ONLINE_USERS,NEW_MESSAGE,STOP_TYPING,START_TYPING}